2025-01-22 16:58:16 - Server listening on ('0.0.0.0', 3102)
2025-01-22 16:58:16 - Public server ip: 46.121.4.35, local server ip: 192.168.1.247
2025-01-22 16:58:16 - Main thread: before accepting ...
2025-01-22 16:58:18 - New Client number 1 from ('192.168.1.247', 58675)
2025-01-22 16:58:53 - Client 1 disconnected
2025-01-22 16:58:53 - Client 1 Exit
2025-01-22 21:40:37 - Server listening on ('0.0.0.0', 3102)
2025-01-22 21:40:37 - Public server ip: 46.121.4.35, local server ip: 192.168.1.122
2025-01-22 21:40:37 - Main thread: before accepting ...
2025-01-22 21:40:42 - New Client number 1 from ('192.168.1.122', 52963)
2025-01-22 21:41:05 - Client 1 disconnected
2025-01-22 21:41:05 - Client 1 Exit
2025-01-22 21:48:54 - Server listening on ('0.0.0.0', 3102)
2025-01-22 21:48:54 - Public server ip: 46.121.4.35, local server ip: 192.168.1.122
2025-01-22 21:48:54 - Main thread: before accepting ...
2025-01-22 21:48:56 - New Client number 1 from ('192.168.1.122', 53069)
2025-01-22 21:49:33 - Client 1 disconnected
2025-01-22 21:49:33 - Client 1 Exit
2025-01-22 22:03:00 - Server listening on ('0.0.0.0', 3102)
2025-01-22 22:03:00 - Public server ip: 46.121.4.35, local server ip: 192.168.1.122
2025-01-22 22:03:01 - Main thread: before accepting ...
2025-01-22 22:03:03 - New Client number 1 from ('192.168.1.122', 53169)
2025-01-22 22:03:05 - Client 1 disconnected
2025-01-22 22:03:05 - Client 1 Exit
2025-01-22 22:08:14 - Server listening on ('0.0.0.0', 3102)
2025-01-22 22:08:15 - Public server ip: 46.121.4.35, local server ip: 192.168.1.122
2025-01-22 22:08:15 - Main thread: before accepting ...
2025-01-22 22:08:17 - New Client number 1 from ('192.168.1.122', 53241)
2025-01-22 22:09:53 - Client 1 disconnected
2025-01-22 22:09:53 - Client 1 Exit
2025-01-22 22:09:55 - New Client number 2 from ('192.168.1.122', 53270)
2025-01-22 22:11:08 - Client 2 disconnected
2025-01-22 22:11:08 - Client 2 Exit
2025-01-22 22:11:17 - New Client number 3 from ('192.168.1.122', 53284)
2025-01-22 22:12:44 - Client 3 disconnected
2025-01-22 22:12:44 - Client 3 Exit
2025-01-22 22:12:48 - New Client number 4 from ('192.168.1.122', 53296)
2025-01-22 22:13:06 - Key values already exist in table
2025-01-22 22:13:54 - Client 4 disconnected
2025-01-22 22:13:54 - Client 4 Exit
2025-01-22 22:14:10 - New Client number 5 from ('192.168.1.122', 53360)
2025-01-22 22:14:26 - Key values already exist in table
2025-01-22 22:14:43 - Client 5 disconnected
2025-01-22 22:14:43 - Client 5 Exit
2025-01-24 15:04:42 - Server listening on ('0.0.0.0', 3102)
2025-01-24 15:04:43 - Public server ip: 46.121.4.35, local server ip: 192.168.1.247
2025-01-24 15:04:43 - Main thread: before accepting ...
2025-01-24 15:04:52 - New Client number 1 from ('192.168.1.247', 61970)
2025-01-24 15:04:56 - Client 1 disconnected
2025-01-24 15:04:56 - Client 1 Exit
2025-02-06 08:03:36 - Server listening on ('0.0.0.0', 3102)
2025-02-06 08:03:37 - Public server ip: 77.137.180.134, local server ip: 172.16.20.119
2025-02-06 08:03:37 - Main thread: before accepting ...
2025-02-06 08:04:19 - New Client number 1 from ('172.16.13.122', 54806)
2025-02-06 08:05:48 - Client 1 disconnected
2025-02-06 08:05:48 - Client 1 Exit
2025-02-06 08:06:34 - New Client number 2 from ('172.16.13.229', 52579)
2025-02-06 08:10:21 - Traceback (most recent call last):
  File "C:\Users\idanh\Desktop\Cyber\My Projects\Final-Project\Main\server\modules\client_requests.py", line 539, in clean_db
    os.remove(self.server_path + "\\cloud\\" + name)
PermissionError: [WinError 32] The process cannot access the file because it is being used by another process: 'C:\\Users\\idanh\\Desktop\\Cyber\\My Projects\\Final-Project\\Main\\server\\cloud\\a089c3b908aa444282f58b18d1ecc314.lock'
2025-02-06 08:15:58 - Client 2 disconnected
2025-02-06 08:15:58 - Client 2 Exit
